# Couleurs & Symboles
RESET="\e[Om"
BOLD="\e[1m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m" 
CYAN="\e[36m"
OK="${BOLD}${GREEN}\u2705${RESET}"
ERR="${BOLD}${RED}\u274C${RESET}"
WARN="${BOLD}${YELLOW}\u26A1${RESET}"
INF="${BOLD}${CYAN}\u2755${RESET}"
